export default {
  translation: {
    places: "places",
    place: "place",
    theme: "Theme",
    defaultTheme: "Default Theme",
    darkTheme: "Dark Theme",
    lightTheme: "Light Theme",
    typeSomeThing: "Type Something...",
    // add address
    addingShippingAddress: "Adding Shipping Address",
    area: "Area",
    streetName: "Street Name",
    buildingType: "Building Type",
    buildingName: "Building Name/Number",
    floorNo: "Floor Number",
    apartmentNumber: "Apartment Number",
    addressName: "Address name (my apartment/my office/etc.)",
    landmark: "Landmark, group number, etc.",
    mobileNo: "Mobile Number",
    landlineNo: "Landline Number",
    saveAddress: "Save Address",
    // addresses
    addAddress: "Add Address",
    shippingAddresses: "Shipping Addresses",
    useAsTheShippingAddress: "Use as the shipping address",
    mobile: "Mobile",
    edit: "Edit",
    // rating and reviiews
    ratingAndReviews: "Rating And Reviews",
    reviews: "Reviews",
    rate: "Rate",
    ratings: "Ratings",
    writeAReview: "Write a review",
    addingReview: "Adding Review",
    pleaseShareYourOpinion: "Please share your opinion.",
    whatIsYouRate: "What is you rate?",
    sendReview: "Send review",
    addYourPhotos: "Add your photos",
    // login
    login: "Login",
    email: "Email",
    password: "Password",
    FYP: "Forgot your password?",
    orLoginWith: "Or login with social account",
    passwordValidationMsg:
      "Minimum six characters, at least one uppercase letter, one lowercase letter, one number and one special character.",
    emailValidationMsg:
      "Not a valid email address. Should be hossambasha9900@gmail.com",
    createNewAccount: "Create new account",
    // register
    signUp: "Sign up",
    name: "Name",
    confirmPassword: "Confirm password",
    alreadyHaveAnAccount: "Already have an account?",
    confirmPasswordValidationMsg: "confirmPasswordValidationMsg",
    orSignUpWith: "Or sign up with social account",
    // forgot password
    forgotPassNote:
      "Please, enter your email address. You will receive a link to create a new password via email.",
    forgotPassword: "Forgot password",
    send: "Send",
    // change Password
    changePassword: "Change Password",
    save: "Save",
    oldPassword: "Old password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm new password",
  },
};
